### PR TITLE
Tidy up finding growth configs, grow chunks on load

### PR DESCRIPTION
**Pull request by pruby**
This should grow chunks on load, even if the plant data is still persistently held.

It refactors a lot of messy code - every different type of growth (hit with stick, growth events, on chunk load) has been finding the configuration to load a block in a different way. This pulls that in to a couple of methods on the main plugin class which can find the growth config for a block or tree type.

Substantial testing recommended, especially around persistence and trees.

### CODE REVIEW

**Comment by pruby** [comment]
This is the fix for the issues with blocks not growing when you leave and return to chunks.

**Comment by ttk2** [comment]
yup thanks, merged and if I can get a .jar that would be great.

**Comment by pruby** [comment]
Package containing this on https://github.com/pruby/RealisticBiomes/tree/package, contains this change and _not_ the pests.

**Comment by ttk2** [comment]
this crashed on startup, does it expect the fishing limitation
configuration at the bottom of the config like the currently live version?
It gave yaml parsing errors.

**Comment by pruby** [comment]
Hmm, config shouldn't have changed at all, just Java code. Can post current live config and the error?

**Comment by ttk2** [comment]
sure

[22:21:25] [Server thread/INFO]: [RealisticBiomes] Enabling RealisticBiomes
v0.6.3.123
[22:21:25] [Server thread/INFO]: [RealisticBiomes] name of logger is:
com.untamedears.realisticbiomes.RealisticBiomes
[22:21:25] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while scanning for
the next token
found character  '\t(TAB)' that cannot start any token. (Do not use \t(TAB)
for indentation)
 in 'string', line 261, column 1:

```
^
```

at
org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149)
~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:204)
[spigot.jar:git-Spigot-1366]
at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:154)
[spigot.jar:git-Spigot-1366]
at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:144)
[spigot.jar:git-Spigot-1366]
at
com.untamedears.realisticbiomes.RealisticBiomes.onEnable(RealisticBiomes.java:72)
[RealisticBiomes.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:462)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:380)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:351)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:326)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:282)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:186)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:440)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[spigot.jar:git-Spigot-1366]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for
the next token; found character  '\t(TAB)' that cannot start any token. (Do
not use \t(TAB) for indentation);  in 'string', line 261, column 1:

```
^
```

at
org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
~[spigot.jar:git-Spigot-1366]
... 16 more
[22:21:25] [Server thread/ERROR]: Cannot load configuration from stream
org.bukkit.configuration.InvalidConfigurationException: while scanning for
the next token
found character  '\t(TAB)' that cannot start any token. (Do not use \t(TAB)
for indentation)
 in 'string', line 261, column 1:

```
^
```

at
org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55)
~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:149)
~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:204)
[spigot.jar:git-Spigot-1366]
at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:154)
[spigot.jar:git-Spigot-1366]
at
com.untamedears.realisticbiomes.RealisticBiomes.onEnable(RealisticBiomes.java:76)
[RealisticBiomes.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:462)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:380)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:351)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:326)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:282)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:186)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:440)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[spigot.jar:git-Spigot-1366]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning for
the next token; found character  '\t(TAB)' that cannot start any token. (Do
not use \t(TAB) for indentation);  in 'string', line 261, column 1:

```
^
```

at
org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:230)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:237)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:159)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
~[spigot.jar:git-Spigot-1366]
at
org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
~[spigot.jar:git-Spigot-1366]
at org.yaml.snakeyaml.Yaml.load(Yaml.java:400) ~[spigot.jar:git-Spigot-1366]
at
org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53)
~[spigot.jar:git-Spigot-1366]
... 15 more
[22:21:25] [Server thread/INFO]: [RealisticBiomes] Persistence enabled: true
[22:21:25] [Server thread/INFO]: [RealisticBiomes] Database: tekkit
[22:21:25] [Server thread/INFO]: [RealisticBiomes] Logging enabled
[22:21:25] [Server thread/INFO]: [RealisticBiomes] Load event minimum time
to log: 5ms
[22:21:25] [Server thread/INFO]: [RealisticBiomes] Unload event minimum
time to log: 5ms
[22:21:25] [Server thread/ERROR]: Error occurred while enabling
RealisticBiomes v0.6.3.123 (Is it up to date?)
java.lang.NullPointerException
at
com.untamedears.realisticbiomes.RealisticBiomes.loadFishConfigs(RealisticBiomes.java:248)
~[?:?]
at
com.untamedears.realisticbiomes.RealisticBiomes.onEnable(RealisticBiomes.java:83)
~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:250)
~[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.loadPlugin(CraftServer.java:462)
[spigot.jar:git-Spigot-1366]
at
org.bukkit.craftbukkit.v1_7_R2.CraftServer.enablePlugins(CraftServer.java:380)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.n(MinecraftServer.java:351)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.g(MinecraftServer.java:326)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.MinecraftServer.a(MinecraftServer.java:282)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.DedicatedServer.init(DedicatedServer.java:186)
[spigot.jar:git-Spigot-1366]
at
net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:440)
[spigot.jar:git-Spigot-1366]
at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[spigot.jar:git-Spigot-1366]

attaching the config.

**Comment by pruby** [comment]
Found a tab in the config file. This seems to indicate though that the config in github isn't the same as the live config (or that would be failing). Tab was around Acacia section of the config.

I think Github ignored the attachment - maybe in dev group? Will have to create another pull request to fix this, but would like to compare to the current live one so you can be aware of any other change it might introduce.

**Comment by ttk2** [comment]
I emailed you the config and I am putting the current github one into
testing.

**Pull request merged**
