### PR TITLE
Fixed chunk loading problem along with other optimizations 

### PR DESCRIPTION
**Pull request by dquist**

### CODE REVIEW

**Comment by axus** [comment]
For your change to irrigation, isn't that requiring the crop to be in a river biome instead of adjacent to?  Not that i know of anything using that rule

**Comment by dquist** [comment]
I'm not sure what you are referring to, I didn't make any change to irrigation that I know of. File? Line number?

**Comment by axus** [comment]
src/com/untamedears/realisticbiomes/GrowthConfig.java line 247 removed.  Uses the biome of the block instead of the water blocks, right?

**Comment by dquist** [comment]
Ah I see, thank you. I was trying to debug a biome bug that ended up being a problem with the bukkit build I was using at the time. I've made the fix to revert it to how it should be.

**Comment by ttk2** [comment]
is that in this pull or a different one?

**Comment by dquist** [comment]
This pull is fixed in the last commit shown.

**Comment by ttk2** [comment]
anyone have anything else they would like to bring up?

**Comment by waffle-stomper** [comment]
One small nitpick - 'chunkCoords' is misspelled as 'chunckCoords' three times in RealisticBiomes.java (lines 385, 388, and 389). It doesn't really matter though, since the misspelling is consistent through that function.

**Pull request merged**
