### PR TITLE
Updated for Acacia and Dark Oak

### PR DESCRIPTION
**Pull request by ribagi**
Acacia are at 2 in hot_dry, 1.0 at Plains.

Dark Oak are at 2 in Forest, 1 at cold_forest.

### CODE REVIEW

**Comment by ttk2** [comment]
how are they treated now without configuration values?

**Comment by ribagi** [comment]
Right now they will default to tree.type TREE, which is the Small Oak Tree.

**Comment by WildWeazel** [comment]
Looks fine. Personally I'd rather see Dark Oak in swamp than another tree type in forests.

**Comment by ribagi** [comment]
Ah, I forgot swamp biomes exists. Yea, I agree. I will put a pull right now.

**Comment by ttk2** [comment]
so close this one?

**Comment by WildWeazel** [comment]
yeah, looks good

**Comment by WildWeazel** [comment]
ttk, I just realized you closed this without merging. It's good if you include all 3 commits. (Not that it will do anything until the new factories are online)

**Comment by ttk2** [comment]
I asked if I should close it and you said yes.

**Pull request closed without merging**
