### PR TITLE
Updated for Acacia and Dark Oak

### PR DESCRIPTION
**Pull request by ribagi**
ACACIA at 2.0 in hot_dry, 1.0 in PLAINS

DARK_OAK 2.0 in swamp, 1.0 in forest, 0.5 in cold_forest

Both inherits from tree and overwrites defaults biomes to 0.

### CODE REVIEW

**Comment by ttk2** [comment]
ok then, these controversial at all?

**Comment by ribagi** [comment]
http://www.reddit.com/r/Civcraft/comments/1z3qys/dark_oak_and_acacia/

There was a conversation about it and it basically mirrored what I had. The numbers I had copied from the other trees, and assumed that it was balanced.

**Comment by WildWeazel** [comment]
I approve, this was pretty much agreed upon previously

**Comment by ttk2** [comment]
did we make any changes to the live config from whats here?

**Pull request merged**
