### PR TITLE
Requested Dispenser Fixes

### PR DESCRIPTION
**Pull request by TeaJizzle**
Disabled bonemeal being used by dispensers on tilled soil and crops.

### CODE REVIEW

**Comment by ttk2** [comment]
this is the one that generates the chunk unload error?

**Comment by TeaJizzle** [comment]
Yes, but I did it when I was exhausted at 5am, might just have been
something daft.

I'll give it another compile and test it again on a fresh server. Does RB
have any dependencies?

**Comment by mgrandi** [comment]
No it doesn't but I added to your commits and am generating a new pull request

**Comment by mgrandi** [comment]
see https://github.com/ttk2/RealisticBiomes/pull/2

**Pull request merged**
