### PR TITLE
Remove tab in YAML file

### PR DESCRIPTION
**Pull request by pruby**

### CODE REVIEW

**Comment by ttk2** [comment]
what exactly does this fix?

**Comment by pruby** [comment]
Was a stray tab in the config file here, was behind the error seen.

**Comment by ttk2** [comment]
config will be updated and tested tomorrow then.

**Comment by pruby** [comment]
Sorry, please wait on that. I hadn't had a chance to look at the file due to a mad day. Another pull request put in to integrate the configurations on live and here.

**Pull request merged**
